blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/scikit-learn/scikit-learn/discussions/new
    about: Ask questions and discuss with other scikit-learn community members
  - name: Blank issue
    url: https://github.com/scikit-learn/scikit-learn/issues/new
    about: Please note that GitHub Discussions should be used in most cases instead