blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/INFOM126-Automated-Software-Engineering/2048-groupe-02/discussions/new/choose
    about: Ask questions and discuss with other scikit-learn community members
  - name: Blank issue
    url: https://github.com/INFOM126-Automated-Software-Engineering/2048-groupe-02/issues/new
    about: Please note that GitHub Discussions should be used in most cases instead