name: Close state issues
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Mark Stale Issues
        uses: actions/stale@v7
        with:
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          stale-pr-message: "This PR has been marked as stale due to inactivity."
          days-before-stale: 2
          days-before-close: 1
          exempt-issue-labels: 'do-not-close'