name: Docker Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn --batch-mode clean package

      # Step 4: Build Docker image with the generated JAR
      - name: Build Docker image
        run: docker build -t 2048:latest .

       #Optional Step 5: Push Docker image to a registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker image
        run: docker push 2048:latest