name: Handle issues

on:
  issues:
    types: [opened]

jobs:
  tag-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check user contribution preference
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define the messages and labels based on the user's choice
          if [[ "$ISSUE_BODY" == *"Yes, I would like to contribute"* ]]; then
            gh issue comment $ISSUE_NUMBER --body "Thank you for volunteering to contribute! Please refer to our [Contributor's Guide](docs/CONTRIBUTOR.md) if you need help to get started. If you have any questions, feel free to contact us!"
            gh issue edit $ISSUE_NUMBER --add-label "contribution intent"
          elif [[ "$ISSUE_BODY" == *"Yes, but I’m not sure how to contribute"* ]]; then
            gh issue comment $ISSUE_NUMBER --body "Thanks for your interest in contributing! It looks like you'd like some help to get started. Please refer to our [Contributor's Guide](https://github.com/INFOM126-Automated-Software-Engineering/2048-groupe-02/blob/main/docs/CONTRIBUTOR.md) for more information, and feel free to ask questions! We have tagged this issue with 'Help requested' to get the attention of our contributors."
            gh issue edit $ISSUE_NUMBER --add-label "help requested"
          elif [[ "$ISSUE_BODY" == *"No, I just want to suggest the improvement"* ]]; then
            echo "No action needed as the user does not want to contribute."
          else
            echo "No recognized response in issue body."
          fi