name: Checkstyle Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - hotfix/*
      - v/*
      - feature/*

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.5.0/checkstyle-10.5.0-all.jar -O checkstyle.jar

    - name: Run Checkstyle
      run: |
        java -jar checkstyle.jar -c /google_checks.xml src/
