name: Checkstyle Linter

on:
  push:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.5.0/checkstyle-10.5.0-all.jar -O checkstyle.jar

    - name: Run Checkstyle
      run: |
        java -jar checkstyle.jar -c /google_checks.xml src/
