name: Java Maven Build & Publish Artifact (.Jar)

on: workflow_dispatch
#  pull_request:
#    branches: [ "Maven" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - name: Create and upload Package.zip
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      - name: Create and upload Package.zip
#        run: echo "Pour lancer le fichier java\:"
        run: echo "java -cp target/2048-1.0-SNAPSHOT.jar be.unamur.game2048.Game"
