name: Java Compilation, Maven, and Test

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
    paths-ignore: ['**.md', 'docs/**', '.gitignore']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Coverage
        run: mvn -B test jacoco:report

      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

  compile:
    runs-on: ubuntu-latest
    needs: test # Ensures the compile stage runs only if the test stage succeeds
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package Without Tests
        run: mvn -B package -DskipTests
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: target/*.jar