name: CI-Telemetry

on:
  push:
    branches:
      - main
      - add_telemetry
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Verify Maven
        run: mvn --version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download OpenTelemetry Java Agent
        run: curl -sSL -o opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

      - name: Collect Build Metrics
        run: |
          # Préparation du fichier metrics.txt
          echo "=== Build Metrics ===" > metrics.txt

          # Temps de début
          START=$(date +%s)
          echo "Start Time: $(date -d @$START)" >> metrics.txt

          # Mémoire avant compilation
          echo "Memory Usage Before Build:" >> metrics.txt
          free -m >> metrics.txt

          # Compilation et métriques détaillées
          echo "=== Compilation Details ===" >> metrics.txt
          /usr/bin/time -v mvn clean install 2>&1 | tee -a metrics.txt

          # Temps de fin
          END=$(date +%s)
          echo "End Time: $(date -d @$END)" >> metrics.txt
          echo "Total Build Time: $(($END - $START)) seconds" >> metrics.txt

          # Mémoire après compilation
          echo "Memory Usage After Build:" >> metrics.txt
          free -m >> metrics.txt

          # Utilisation CPU globale
          echo "=== CPU Usage ===" >> metrics.txt
          top -bn1 | grep "Cpu(s)" >> metrics.txt

          # Utilisation spécifique par Maven
          echo "=== Top Processes ===" >> metrics.txt
          ps aux --sort=-%cpu | head -n 10 >> metrics.txt

      - name: Upload Metrics Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-metrics
          path: metrics.txt
