name: CI-Telemetry

on:
  push:
    branches:
      - main
      - add_telemetry
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer le JDK (Java 17, ajustez si nécessaire)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 3 : Mettre en cache les dépendances Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Étape 4 : Télécharger l'agent OpenTelemetry
      - name: Download OpenTelemetry Java Agent
        run: curl -sSL -o opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

      # Étape 5 : Mesurer le temps de compilation et collecter des métriques
      - name: Build and collect metrics
        run: |
          START=$(date +%s) # Démarrer le chronomètre
          java -javaagent:./opentelemetry-javaagent.jar \
            -Dotel.metrics.exporter=none \
            -Dotel.traces.exporter=none \
            -Dotel.logs.exporter=stdout \
            mvn clean install
          END=$(date +%s) # Arrêter le chronomètre
          echo "Build Time: $(($END - $START)) seconds"

      # Étape 6 : Afficher les ressources système utilisées
      - name: Display Resource Usage
        run: |
          echo "CPU Usage:"
          top -bn1 | grep "Cpu(s)"
          echo "Memory Usage:"
          free -m
