name: CI-Telemetry

on:
  push:
    branches:
      - main
      - add_telemetry
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Verify Maven
        run: mvn --version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download OpenTelemetry Java Agent
        run: curl -sSL -o opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

      - name: Build and collect metrics
        run: |
          START=$(date +%s)
          java -javaagent:./opentelemetry-javaagent.jar \
            -Dotel.metrics.exporter=none \
            -Dotel.traces.exporter=none \
            -Dotel.logs.exporter=none \
            mvn clean install
          END=$(date +%s)
          echo "Build Time: $(($END - $START)) seconds"

      - name: Display Resource Usage
        run: |
          echo "CPU Usage:"
          top -bn1 | grep "Cpu(s)"
          echo "Memory Usage:"
          free -m
